version: 2

builds:
  - dir: forge-cli
    main: ./cmd/forge
    binary: forge
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      forge-
      {{- title .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

brews:
  - name: forge
    repository:
      owner: initializ
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/initializ/forge"
    description: "Forge is a secure, portable AI Agent runtime. Run agents locally, in cloud, or enterprise environments without exposing inbound tunnels."
    license: "Apache-2.0"
    install: |
      bin.install "forge"
    test: |
      system "#{bin}/forge", "--version"
    commit_author:
      name: "forge-bot"
      email: "forge-bot@initializ.ai"
    commit_msg_template: "chore: update forge formula to {{ .Tag }}"
