package runtime

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"io"
	"sync"
	"time"
)

// Audit event type constants.
const (
	AuditSessionStart     = "session_start"
	AuditSessionEnd       = "session_end"
	AuditToolExec         = "tool_exec"
	AuditEgressAllowed    = "egress_allowed"
	AuditEgressBlocked    = "egress_blocked"
	AuditLLMCall          = "llm_call"
	AuditGuardrail        = "guardrail_check"
	AuditScheduleFire     = "schedule_fire"
	AuditScheduleComplete = "schedule_complete"
	AuditScheduleSkip     = "schedule_skip"
	AuditScheduleModify   = "schedule_modify"

	// Auth events. Carry no PII (no email, no claims, no token bytes) —
	// only the audit subject (UserID), tenant (OrgID), and structural
	// metadata. See the auth-package middleware for the emitter.
	EventAuthVerify = "auth_verify" // every successful auth decision
	EventAuthFail   = "auth_fail"   // every failed auth decision (with reason code)

	// MCP events. Like auth, these carry NO byte payload — never the
	// arguments to a tool call, never the result content. Emitters
	// include only sizes (args_size, result_size), durations, server +
	// tool names, and reason codes. See forge-core/mcp and
	// forge-core/tools/adapters/mcp_tool.go.
	EventMCPServerStarted  = "mcp_server_started"
	EventMCPServerFailed   = "mcp_server_failed"
	EventMCPServerDegraded = "mcp_server_degraded"
	EventMCPToolCall       = "mcp_tool_call"
	EventMCPToolResult     = "mcp_tool_result"
	EventMCPToolConflict   = "mcp_tool_conflict"
	EventMCPTokenRefresh   = "mcp_token_refresh"

	// Agent Card events. Emitted once at agent startup with the
	// finalized A2A Agent Card content for traceability. Carries the
	// card's name, version, URL, protocolVersion, skill count, and a
	// sha256 hash of the JSON-encoded card so consumers can detect
	// config drift. See forge-cli/runtime/runner.go's startup pass
	// and the A2A 0.3.0 spec.
	EventAgentCardPublished = "agent_card_published"

	// Deprecated: use EventAuthVerify. Kept as a string alias so any
	// audit-log consumer that grep'd for "auth_success" can be migrated.
	// Scheduled for removal in v0.11.0.
	AuditAuthSuccess = EventAuthVerify
	// Deprecated: use EventAuthFail. Same migration window as AuditAuthSuccess.
	AuditAuthFailure = EventAuthFail
)

// AuditEvent is a single structured audit record emitted as NDJSON.
//
// Workflow correlation fields (WorkflowID, StageID, StepID,
// InvocationCaller) are tagged onto every event emitted via
// EmitFromContext when the request carries `X-Workflow-*` /
// `X-Invocation-Caller` headers from any A2A-compatible orchestrator.
// Direct A2A invocations omit them entirely so the JSON shape matches
// the pre-FWS-2 audit consumers.
type AuditEvent struct {
	Timestamp string `json:"ts"`
	Event     string `json:"event"`

	// CorrelationID groups events from a single agent invocation —
	// generated by the A2A handler at request entry.
	CorrelationID string `json:"correlation_id,omitempty"`

	// TaskID is the A2A task identifier (params.id on tasks/send).
	TaskID string `json:"task_id,omitempty"`

	// WorkflowID identifies the orchestrator-level workflow run that
	// invoked this agent. Sourced from X-Workflow-ID at request entry;
	// absent for direct A2A invocations.
	WorkflowID string `json:"workflow_id,omitempty"`

	// StageID identifies the workflow stage that invoked this agent.
	StageID string `json:"stage_id,omitempty"`

	// StepID identifies the workflow step that invoked this agent.
	StepID string `json:"step_id,omitempty"`

	// InvocationCaller identifies the upstream caller (orchestrator
	// or upstream agent in an agent-to-agent flow).
	InvocationCaller string `json:"invocation_caller,omitempty"`

	Fields map[string]any `json:"fields,omitempty"`
}

// AuditLogger writes structured NDJSON audit events to an io.Writer.
type AuditLogger struct {
	mu sync.Mutex
	w  io.Writer
}

// NewAuditLogger creates a new AuditLogger writing to w.
func NewAuditLogger(w io.Writer) *AuditLogger {
	return &AuditLogger{w: w}
}

// Emit writes an audit event as a single NDJSON line. If Timestamp is empty
// it is set to the current time in RFC3339 format.
//
// Callers that have a request context.Context in scope should prefer
// EmitFromContext, which automatically tags CorrelationID, TaskID, and
// the workflow-correlation fields (WorkflowID, StageID, StepID,
// InvocationCaller) from the context. Emit is kept for the few sites
// that emit outside a request scope (e.g. agent_card_published at
// startup).
func (a *AuditLogger) Emit(event AuditEvent) {
	if event.Timestamp == "" {
		event.Timestamp = time.Now().UTC().Format(time.RFC3339)
	}
	data, err := json.Marshal(event)
	if err != nil {
		return
	}
	data = append(data, '\n')

	a.mu.Lock()
	a.w.Write(data) //nolint:errcheck
	a.mu.Unlock()
}

// EmitFromContext writes an audit event after auto-tagging
// CorrelationID, TaskID, and workflow-correlation fields from the
// request context. Fields already set on the passed event are
// preserved — the context is a fallback, not an override. This makes
// it safe to migrate callers from Emit to EmitFromContext: any
// already-explicit value continues to win.
func (a *AuditLogger) EmitFromContext(ctx context.Context, event AuditEvent) {
	if event.CorrelationID == "" {
		event.CorrelationID = CorrelationIDFromContext(ctx)
	}
	if event.TaskID == "" {
		event.TaskID = TaskIDFromContext(ctx)
	}
	if event.WorkflowID == "" || event.StageID == "" || event.StepID == "" || event.InvocationCaller == "" {
		wc := WorkflowContextFromContext(ctx)
		if event.WorkflowID == "" {
			event.WorkflowID = wc.WorkflowID
		}
		if event.StageID == "" {
			event.StageID = wc.StageID
		}
		if event.StepID == "" {
			event.StepID = wc.StepID
		}
		if event.InvocationCaller == "" {
			event.InvocationCaller = wc.InvocationCaller
		}
	}
	a.Emit(event)
}

// Context key types for correlation IDs, task IDs, and file directories.
type correlationIDKey struct{}
type taskIDKey struct{}
type filesDirKey struct{}

// WithCorrelationID stores a correlation ID in the context.
func WithCorrelationID(ctx context.Context, id string) context.Context {
	return context.WithValue(ctx, correlationIDKey{}, id)
}

// CorrelationIDFromContext retrieves the correlation ID from the context.
// Returns "" if not set.
func CorrelationIDFromContext(ctx context.Context) string {
	if id, ok := ctx.Value(correlationIDKey{}).(string); ok {
		return id
	}
	return ""
}

// WithTaskID stores a task ID in the context.
func WithTaskID(ctx context.Context, id string) context.Context {
	return context.WithValue(ctx, taskIDKey{}, id)
}

// TaskIDFromContext retrieves the task ID from the context.
// Returns "" if not set.
func TaskIDFromContext(ctx context.Context) string {
	if id, ok := ctx.Value(taskIDKey{}).(string); ok {
		return id
	}
	return ""
}

// WithFilesDir stores a files directory path in the context.
func WithFilesDir(ctx context.Context, dir string) context.Context {
	return context.WithValue(ctx, filesDirKey{}, dir)
}

// FilesDirFromContext retrieves the files directory from the context.
// Returns "" if not set.
func FilesDirFromContext(ctx context.Context) string {
	if dir, ok := ctx.Value(filesDirKey{}).(string); ok {
		return dir
	}
	return ""
}

// GenerateID produces a 16-character hex random ID using crypto/rand.
func GenerateID() string {
	b := make([]byte, 8)
	if _, err := rand.Read(b); err != nil {
		// Fallback: return a fixed string (should never happen in practice)
		return "0000000000000000"
	}
	return hex.EncodeToString(b)
}
