// Package observability constructs the real OTLP tracer provider Forge
// hands to the runtime seam in forge-core/runtime/tracing.go.
//
// This package is pure library — it does NOT read forge.yaml, env, or
// CLI flags. Configuration arrives as a fully-resolved TracingConfig
// from the cli-level wiring (Phase 2 of the OTel v1 initiative, #103).
// Anti-coupling: the runtime seam in forge-core/runtime depends only
// on the OTel TracerProvider interface; this package supplies a real
// SDK implementation that the cli installs at startup.
//
// See issue #102 (Phase 1) and the master tracking issue #108.
package observability

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"strings"
	"time"

	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/exporters/otlp/otlptrace"
	"go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc"
	"go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp"
	"go.opentelemetry.io/otel/sdk/resource"
	sdktrace "go.opentelemetry.io/otel/sdk/trace"
	semconv "go.opentelemetry.io/otel/semconv/v1.26.0"
)

// Protocol values recognized by TracingConfig.Protocol. The OTLP spec
// allows additional encodings; Forge ships HTTP+protobuf (the default,
// port 4318 convention) and gRPC (port 4317). HTTP+JSON is deliberately
// not exposed — backends that need it can configure their collector to
// translate, and Forge's own egress-allowlist wiring (Phase 6) tracks
// the host, not the encoding.
const (
	ProtocolHTTPProtobuf = "http/protobuf"
	ProtocolGRPC         = "grpc"
)

// Sampler values recognized by TracingConfig.Sampler. The string set is
// the same one the OTEL_TRACES_SAMPLER env var documents, so operators
// who already know the standard names don't have to learn Forge-
// specific ones.
const (
	SamplerAlwaysOn                = "always_on"
	SamplerAlwaysOff               = "always_off"
	SamplerTraceIDRatio            = "traceidratio"
	SamplerParentBasedAlwaysOn     = "parentbased_always_on"
	SamplerParentBasedAlwaysOff    = "parentbased_always_off"
	SamplerParentBasedTraceIDRatio = "parentbased_traceidratio"
)

// Defaults applied when TracingConfig leaves a field at the zero
// value. Centralized here so the cli flag layer (Phase 2) and the
// tests reference the same constants.
const (
	DefaultProtocol     = ProtocolHTTPProtobuf
	DefaultSampler      = SamplerParentBasedAlwaysOn
	DefaultSamplerRatio = 1.0
	DefaultTimeout      = 10 * time.Second
)

// ErrDisabled is returned by NewTracerProvider when cfg.Enabled is
// false. Distinct sentinel so the cli wiring can branch on it
// (`errors.Is(err, ErrDisabled) → install the no-op tracer`) without
// turning a legitimate "tracing off" state into a startup error.
var ErrDisabled = errors.New("tracing disabled")

// TracingConfig is the fully-resolved tracing configuration passed
// from the cli layer. Pure data — no env, no file lookups. Phase 2
// (#103) resolves env / forge.yaml / CLI-flag precedence and hands a
// finished TracingConfig to NewTracerProvider.
type TracingConfig struct {
	// Enabled gates the whole subsystem. When false, NewTracerProvider
	// returns (nil, ErrDisabled) and the cli installs the noop tracer.
	// Default false (off-by-default per the initiative ruling).
	Enabled bool

	// Endpoint is the OTLP target URL. For http/protobuf:
	// "https://otel-collector.svc.cluster.local:4318/v1/traces". For
	// gRPC: "otel-collector.svc.cluster.local:4317". Required when
	// Enabled is true; an empty endpoint with Enabled=true is treated
	// the same as Enabled=false (the cli logs a warning and installs
	// the noop tracer — never crash the agent over telemetry config).
	Endpoint string

	// Protocol selects the OTLP encoding + transport. One of
	// ProtocolHTTPProtobuf (default) or ProtocolGRPC. The egress
	// allowlist + NetworkPolicy generated by `forge package` (Phase 6)
	// allowlists the endpoint host, not the encoding.
	Protocol string

	// Sampler is one of the SamplerXxx constants. Default
	// SamplerParentBasedAlwaysOn — when an upstream caller's
	// traceparent header says "sample," we honor it; when no parent
	// context exists, we sample everything. Standard server-side
	// posture.
	Sampler string

	// SamplerRatio applies to the *TraceIDRatio* samplers (0.0 — 1.0).
	// Ignored for the always_on / always_off variants. Default 1.0.
	SamplerRatio float64

	// Headers are OTLP request headers (typically auth tokens).
	// Prefer env-driven values in the cli layer so secrets don't
	// end up committed to forge.yaml.
	Headers map[string]string

	// Timeout bounds each exporter request. Default 10s.
	Timeout time.Duration

	// ServiceName is OTel's `service.name` resource attribute, the
	// primary identifier backends group spans by. The cli layer
	// resolves $OTEL_SERVICE_NAME first, then falls back to the
	// agent_id from forge.yaml. Required when Enabled is true.
	ServiceName string

	// ServiceVersion is OTel's `service.version`. Sourced from the
	// agent's `version` in forge.yaml.
	ServiceVersion string

	// RuntimeVersion is the Forge build version, surfaced as
	// `forge.runtime.version`. Lets backends compare agent runs across
	// Forge upgrades.
	RuntimeVersion string

	// ResourceAttrs are additional resource attributes merged with the
	// service.* / forge.* attributes above. The cli layer parses
	// $OTEL_RESOURCE_ATTRIBUTES into this map.
	ResourceAttrs map[string]string

	// Redact and CaptureContent are consumed by the Phase 3 span
	// instrumentation, not by this constructor — but they live in the
	// config struct so the cli layer wires every knob in one place.
	// Redact defaults true; CaptureContent defaults false (the
	// enterprise opt-in for prompt/completion content per the
	// initiative ruling).
	Redact         bool
	CaptureContent bool
}

// NewTracerProvider builds a real OTLP-backed sdktrace.TracerProvider
// from a resolved TracingConfig. Returns (nil, ErrDisabled) when the
// config is disabled or has no endpoint — the cli treats both as
// "install the noop tracer" without crashing the agent.
//
// The transport parameter is the egress-enforced http.RoundTripper
// the cli layer supplies (typically the SafeTransport wrapping
// http.DefaultTransport). For ProtocolHTTPProtobuf the transport is
// injected into the OTLP HTTP client so the exporter's traffic flows
// through the same allowlist + post-DNS IP guard every other in-
// process Forge HTTP client uses. For ProtocolGRPC the OTel grpc
// exporter dials directly via grpc.Dial — the egress enforcer cannot
// wrap that path, so for gRPC the endpoint host must be in the build-
// time egress allowlist and Forge relies on the NetworkPolicy +
// (Linux) the agent's outbound firewall to bound the traffic. HTTP is
// the recommended default for that reason.
//
// Caller owns Shutdown. Phase 2's runner wiring calls
// `defer tp.Shutdown(ctx)` at the same lifecycle hook the audit-sink
// Close call lives at, so the batch processor flushes on a clean exit.
func NewTracerProvider(ctx context.Context, cfg TracingConfig, transport http.RoundTripper) (*sdktrace.TracerProvider, error) {
	if !cfg.Enabled || cfg.Endpoint == "" {
		return nil, ErrDisabled
	}
	if cfg.ServiceName == "" {
		return nil, errors.New("observability: TracingConfig.ServiceName is required when Enabled=true")
	}
	// Apply zero-value defaults centrally so the rest of the
	// constructor reads the fully-resolved config without per-field
	// fallback noise.
	protocol := cfg.Protocol
	if protocol == "" {
		protocol = DefaultProtocol
	}
	sampler := cfg.Sampler
	if sampler == "" {
		sampler = DefaultSampler
	}
	ratio := cfg.SamplerRatio
	if ratio <= 0 {
		ratio = DefaultSamplerRatio
	}
	timeout := cfg.Timeout
	if timeout <= 0 {
		timeout = DefaultTimeout
	}

	exporter, err := newExporter(ctx, protocol, cfg.Endpoint, cfg.Headers, timeout, transport)
	if err != nil {
		return nil, fmt.Errorf("observability: building OTLP exporter: %w", err)
	}

	res, err := buildResource(ctx, cfg)
	if err != nil {
		// Resource merge failures are non-fatal in OTel's own model
		// (the SDK falls back to a partial resource) — we surface the
		// error here for visibility but the caller may choose to log
		// and continue. The vast majority of merge failures come from
		// malformed entries in OTEL_RESOURCE_ATTRIBUTES, which an
		// operator wants to see at startup.
		return nil, fmt.Errorf("observability: building resource: %w", err)
	}

	parsedSampler, err := parseSampler(sampler, ratio)
	if err != nil {
		return nil, fmt.Errorf("observability: %w", err)
	}

	tp := sdktrace.NewTracerProvider(
		// Production batching — the SimpleSpanProcessor exists only for
		// tests and would create an exporter round-trip per span on the
		// hot path.
		sdktrace.WithBatcher(exporter),
		sdktrace.WithResource(res),
		sdktrace.WithSampler(parsedSampler),
	)
	return tp, nil
}

// newExporter dispatches on protocol. Errors include the protocol
// name so a misconfigured `protocol: htttp/protobuf` shows up
// loudly at startup instead of silently no-opping.
func newExporter(ctx context.Context, protocol, endpoint string, headers map[string]string, timeout time.Duration, transport http.RoundTripper) (sdktrace.SpanExporter, error) {
	switch protocol {
	case ProtocolHTTPProtobuf:
		opts := []otlptracehttp.Option{
			otlptracehttp.WithEndpointURL(endpoint),
			otlptracehttp.WithTimeout(timeout),
		}
		if len(headers) > 0 {
			opts = append(opts, otlptracehttp.WithHeaders(headers))
		}
		// Inject the caller's egress-enforced transport into the
		// exporter's HTTP client so the OTLP traffic flows through
		// the same allowlist + post-DNS IP guard every other
		// in-process Forge HTTP client uses.
		if transport != nil {
			opts = append(opts, otlptracehttp.WithHTTPClient(&http.Client{
				Transport: transport,
				Timeout:   timeout,
			}))
		}
		client := otlptracehttp.NewClient(opts...)
		return otlptrace.New(ctx, client)
	case ProtocolGRPC:
		opts := []otlptracegrpc.Option{
			otlptracegrpc.WithEndpoint(endpoint),
			otlptracegrpc.WithTimeout(timeout),
		}
		if len(headers) > 0 {
			opts = append(opts, otlptracegrpc.WithHeaders(headers))
		}
		// gRPC exporter constructs its own grpc.ClientConn under the
		// hood; there's no documented hook for an
		// http.RoundTripper-style transport. For gRPC the egress
		// enforcement therefore relies on:
		//   1. The host being in the build-time egress allowlist
		//      (Phase 6 — `forge package` writes this entry into
		//      egress_allowlist.json with source "otel"), and
		//   2. The Kubernetes NetworkPolicy generated alongside the
		//      Deployment manifest.
		// HTTP is the recommended default for Forge agents because
		// the in-process EgressEnforcer can wrap it.
		client := otlptracegrpc.NewClient(opts...)
		return otlptrace.New(ctx, client)
	default:
		return nil, fmt.Errorf("unknown protocol %q (expected %q or %q)", protocol, ProtocolHTTPProtobuf, ProtocolGRPC)
	}
}

// buildResource assembles the OTel Resource Forge attaches to every
// emitted span. service.name + service.version + forge.runtime.version
// are the canonical fields backends key dashboards by; the
// ResourceAttrs map carries operator-supplied extras (parsed from
// $OTEL_RESOURCE_ATTRIBUTES in the cli layer).
func buildResource(ctx context.Context, cfg TracingConfig) (*resource.Resource, error) {
	attrs := []attribute.KeyValue{
		semconv.ServiceName(cfg.ServiceName),
	}
	if cfg.ServiceVersion != "" {
		attrs = append(attrs, semconv.ServiceVersion(cfg.ServiceVersion))
	}
	if cfg.RuntimeVersion != "" {
		// Custom attribute — there's no semconv key for "the agent
		// runtime version distinct from the application version." We
		// namespace as `forge.runtime.version` so backends can group
		// by Forge upgrade waves without confusing it with the
		// service.version of the user's agent.
		attrs = append(attrs, attribute.String("forge.runtime.version", cfg.RuntimeVersion))
	}
	// Stamp the OTel schema URL so backends that key by schema can
	// resolve attribute meanings deterministically. Matches the
	// semconv version this package imports.
	base, err := resource.New(ctx,
		resource.WithSchemaURL(semconv.SchemaURL),
		resource.WithAttributes(attrs...),
	)
	if err != nil {
		return nil, fmt.Errorf("base resource: %w", err)
	}
	if len(cfg.ResourceAttrs) == 0 {
		return base, nil
	}
	extra := make([]attribute.KeyValue, 0, len(cfg.ResourceAttrs))
	for k, v := range cfg.ResourceAttrs {
		extra = append(extra, attribute.String(k, v))
	}
	extraRes, err := resource.New(ctx, resource.WithAttributes(extra...))
	if err != nil {
		return nil, fmt.Errorf("extra resource: %w", err)
	}
	merged, err := resource.Merge(base, extraRes)
	if err != nil {
		return nil, fmt.Errorf("merging extra resource attrs: %w", err)
	}
	return merged, nil
}

// parseSampler maps the standard OTEL_TRACES_SAMPLER string to an OTel
// SDK Sampler. The string set deliberately mirrors the OTel spec's
// names so operators who already know `parentbased_always_on` from
// other instrumentations don't have to learn Forge-specific aliases.
//
// Errors wrap the offending sampler string so a misconfigured
// `parent_based_always_on` (typo) shows up at startup rather than as
// a silent fall-through to a default.
func parseSampler(name string, ratio float64) (sdktrace.Sampler, error) {
	switch strings.ToLower(strings.TrimSpace(name)) {
	case SamplerAlwaysOn:
		return sdktrace.AlwaysSample(), nil
	case SamplerAlwaysOff:
		return sdktrace.NeverSample(), nil
	case SamplerTraceIDRatio:
		return sdktrace.TraceIDRatioBased(ratio), nil
	case SamplerParentBasedAlwaysOn:
		return sdktrace.ParentBased(sdktrace.AlwaysSample()), nil
	case SamplerParentBasedAlwaysOff:
		return sdktrace.ParentBased(sdktrace.NeverSample()), nil
	case SamplerParentBasedTraceIDRatio:
		return sdktrace.ParentBased(sdktrace.TraceIDRatioBased(ratio)), nil
	default:
		return nil, fmt.Errorf("unknown sampler %q (expected one of: %s, %s, %s, %s, %s, %s)",
			name,
			SamplerAlwaysOn, SamplerAlwaysOff, SamplerTraceIDRatio,
			SamplerParentBasedAlwaysOn, SamplerParentBasedAlwaysOff, SamplerParentBasedTraceIDRatio)
	}
}
